### ISSUE TITLE
if AC is not online it will crash homebridge

### ISSUE THREAD

**Issue by duculete** [ddenisyuk/homebridge-gree-heatercooler#1]
[2019-5-30 15:43:41] TypeError: Cannot read property 'Mod' of undefined
    at Device.getMode (/usr/local/lib/node_modules/homebridge-gree-heatercooler/app/deviceFactory.js:284:33)
    at GreeHeaterCooler.getCurrentHeaterCoolerState (/usr/local/lib/node_modules/homebridge-gree-heatercooler/index.js:204:32)
    at Characteristic.CurrentHeaterCoolerState.emit (events.js:182:13)
    at Characteristic.CurrentHeaterCoolerState.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>:null:null)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:182:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by vvsokolov** [comment]
I have the same issue

**Comment by JimHuyiwei** [comment]
I have the same issue.

**Comment by teymur1988** [comment]
I have the same issue. Please help.

**Comment by fleck83** [comment]
Same here...

**Comment by emarrero** [comment]
I fixed deviceFactory.js  change the line  235


this.socket.send(serializedRequest, 0, serializedRequest.length, port, address);

		try {
			this.socket.send(serializedRequest, 0, serializedRequest.length, port, address);
		} catch (error) {
			console.log(error);
		}

**Comment by teymur1988** [comment]
Hey GUys,

Can anyone please advise?!
After updating Homebridge to version 1.0.0 this plugin is the one causing everything not to respond in homekit. If removed from the config.json everything works again. @ddenisyuk perhaps you can help us? 

Regards

Teymur.

**Comment by ddenisyuk** [comment]
Hey, I'm very sorry, but I can't fix and test this plugin due to environment changes. Feel free to open PRs with fixes.

**Comment by teymur1988** [comment]
@ddenisyuk Would you please explain what's PRs ?

**Comment by ddenisyuk** [comment]
Thanks @Elethom for help. 1.0.3 is now available in npm
