### ISSUE TITLE
Error communicating with device

### ISSUE THREAD

**Issue by dsylex** [ddenisyuk/homebridge-gree-heatercooler#11]
Hey there, 

i keep getting the below error even though the AC is working and connected to homebridge, any idea how to get rid of the error spam?

Thanks in advance!

[8/16/2020, 10:48:10 PM] [Office AC] Error communicating with device 1exxxxxd with IP address 192.168.1.6

**Comment by dsylex** [comment]
Update: I have successfully added all ACs in my house and I keep getting these errors for all of them but they work perfectly. It's bugging me a wee bit.

**Comment by netanelassor** [comment]
hi im getting the following error:
RangeError [ERR_SOCKET_BAD_PORT]: Port should be > 0 and < 65536. Received 0.
    at validatePort (internal/validators.js:182:11)
    at Socket.send (dgram.js:599:12)
    at Device._sendRequest (/usr/local/lib/node_modules/homebridge-gree-heatercooler/app/deviceFactory.js:236:25)
    at Device._sendCommand (/usr/local/lib/node_modules/homebridge-gree-heatercooler/app/deviceFactory.js:213:14)
    at Device.setPower (/usr/local/lib/node_modules/homebridge-gree-heatercooler/app/deviceFactory.js:248:14)
    at GreeHeaterCooler.setActive (/usr/local/lib/node_modules/homebridge-gree-heatercooler/index.js:193:25)
    at Active.emit (events.js:315:20)
    at Active.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Active.Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:652:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1437:24 {
  code: 'ERR_SOCKET_BAD_PORT'

**Comment by VasylKhmil** [comment]
This is happing because AC is not responding on initial message sent. So no host information exist. Maybe somebody know why one AC might not respond to this initial message? I have 3 Acs, two works, third one stops working.

**Comment by ddenisyuk** [comment]
@VasylKhmil @netanelassor try to reboot your AC

**Comment by VasylKhmil** [comment]
Didn't help @ddenisyuk

**Comment by alexbartisro** [comment]
> hi im getting the following error:
> RangeError [ERR_SOCKET_BAD_PORT]: Port should be > 0 and < 65536. Received 0.
> at validatePort (internal/validators.js:182:11)
> at Socket.send (dgram.js:599:12)
> at Device._sendRequest (/usr/local/lib/node_modules/homebridge-gree-heatercooler/app/deviceFactory.js:236:25)
> at Device._sendCommand (/usr/local/lib/node_modules/homebridge-gree-heatercooler/app/deviceFactory.js:213:14)
> at Device.setPower (/usr/local/lib/node_modules/homebridge-gree-heatercooler/app/deviceFactory.js:248:14)
> at GreeHeaterCooler.setActive (/usr/local/lib/node_modules/homebridge-gree-heatercooler/index.js:193:25)
> at Active.emit (events.js:315:20)
> at Active.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
> at Active.Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:652:12)
> at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1437:24 {
> code: 'ERR_SOCKET_BAD_PORT'

I also started getting this today.

Edit: a restart to homebridge while the AC was on fixed this.
