### ISSUE TITLE
Crashlops - SetTem

### ISSUE THREAD

**Issue by quartist** [ddenisyuk/homebridge-gree-heatercooler#2]
I have error like this:

TypeError: Cannot read property 'SetTem' of undefined
    at Device.getTemp (/usr/lib/node_modules/homebridge-gree-heatercooler/app/deviceFactory.js:272:33)
    at GreeHeaterCooler.getTargetTemperature (/usr/lib/node_modules/homebridge-gree-heatercooler/index.js:275:36)
    at CoolingThresholdTemperature.emit (events.js:311:20)
    at CoolingThresholdTemperature.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at CoolingThresholdTemperature.Characteristic._this.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:451:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1219:22
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1147:10)
    at HAPServer.emit (events.js:311:20)
    at HAPServer.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:900:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:307:24)
    at IncomingMessage.emit (events.js:311:20)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

any solutions?

**Comment by ddenisyuk** [comment]
Thanks @Elethom for help. 1.0.3 is now available in npm
