### ISSUE TITLE
AC not turning on, switching off after command

### ISSUE THREAD

**Issue by Terabyte1385** [ddenisyuk/homebridge-gree-heatercooler#22]
As I try to turn on the AC, it shows "Cooling to (temperature)" for 2 seconds before returning to "Off". No Homebridge logs whatsoever.
https://user-images.githubusercontent.com/78782971/224620039-729672a3-4c22-4aa7-a6c6-eab21dd0127d.MOV

**EDIT:** I've been able to get these logs:
```
Error communicating with device c6a3a7df with IP address 192.168.0.14
[GreeAC]: _handleResponse error <Buffer 7b 22 74 22 3a 22 70 61 63 6b 22 2c 22 69 22 3a 30 2c 22 75 69 64 22 3a 30 2c 22 63 69 64 22 3a 22 35 30 32 63 63 36 61 33 61 37 64 66 22 2c 22 74 63 ... 106 more bytes> { address: '192.168.0.14', family: 'IPv4', port: 7000, size: 156 } TypeError: Cannot read properties of undefined (reading '0')
    at /homebridge/node_modules/homebridge-gree-heatercooler/app/deviceFactory.js:208:54
    at Array.forEach (<anonymous>)
    at Device._handleResponse (/homebridge/node_modules/homebridge-gree-heatercooler/app/deviceFactory.js:207:26)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-gree-heatercooler/app/deviceFactory.js:60:56)
    at Socket.emit (node:events:513:28)
    at UDP.onMessage (node:dgram:930:8)
```

**Comment by Terabyte1385** [comment]
After debugging a little, it looks like the AC simply stops responding if not pinged in a while. Maybe adding a ping option?
