### ISSUE TITLE
Error  - crash loops

### ISSUE THREAD

**Issue by quartist** [ddenisyuk/homebridge-gree-heatercooler#6]
Hello, 

In new version 1.0.3 my homebridge stop working wit errors:

TypeError: Cannot read property 'SetTem' of undefined
    at Device.getTemp (/usr/lib/node_modules/homebridge-gree-heatercooler/app/deviceFactory.js:272:33)
    at GreeHeaterCooler.getTargetTemperature (/usr/lib/node_modules/homebridge-gree-heatercooler/index.js:275:36)
    at HeatingThresholdTemperature.emit (events.js:315:20)
    at HeatingThresholdTemperature.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HeatingThresholdTemperature.Characteristic._this.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:462:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1215:22
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1143:10)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:756:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:280:24)
    at IncomingMessage.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2020-6-22 16:34:34] Got SIGTERM, shutting down Homebridge...

and:

TypeError: Cannot read property 'Mod' of undefined
    at Device.getMode (/usr/lib/node_modules/homebridge-gree-heatercooler/app/deviceFactory.js:288:33)
    at GreeHeaterCooler.getCurrentHeaterCoolerState (/usr/lib/node_modules/homebridge-gree-heatercooler/index.js:204:32)
    at CurrentHeaterCoolerState.emit (events.js:315:20)
    at CurrentHeaterCoolerState.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at CurrentHeaterCoolerState.Characteristic._this.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:462:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1215:22
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1143:10)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:756:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:280:24)
    at IncomingMessage.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

config:

        {
            "accessory": "GreeHeaterCooler",
            "host": "192.168.100.118",
            "name": "AC B",
            "acModel": "U-Crown",
            "acTempSensorShift": 40,
            "updateInterval": 10000
        },
        {
            "accessory": "GreeHeaterCooler",
            "host": "192.168.100.117",
            "name": "AC A",
            "acModel": "U-Crown",
            "acTempSensorShift": 40,
            "updateInterval": 10000
        }

**Comment by ddenisyuk** [comment]
Do you able to connect and control you AC with EWPE Smart APP?

**Comment by quartist** [comment]
Hi,

yes, that's working good. Using Gree+ app on iOS. Homebridge and AC are in the same LAN network. I would like to help with debug this but I don't have idea how. What type of information you need? I'm using Gree U-Crown AC. Homebridge in version 1.1.0 ; plugin 1.0.3.

**Comment by ghost** [comment]
Just checked the code. Current code base couldn't handle errors very well. Might get a refactor done in a few days if I'm gonna be available.

**Comment by ddenisyuk** [comment]
@quartist please try to connect to your AC with https://github.com/tomikaa87/gree-remote and read the statuses.

**Comment by quartist** [comment]
@ddenisyuk 
sure:

[method]python3 gree.py -c IP -i "id" -k "key" get "parameter"
Parameters:
Getting parameter: Pow
Pow = 0
Getting parameter: Mod
Mod = 1
Getting parameter: SetTem
SetTem = 23
Getting parameter: WdSpd
WdSpd = 0
Getting parameter: Air
Air = 0
Getting parameter: Blo
Blo = 0
Getting parameter: Health
Health = 0
Getting parameter: SwhSlp
SwhSlp = 0
Getting parameter: Lig
Lig = 1
Getting parameter: SwingLfRig
SwingLfRig = 0
Getting parameter: SwUpDn
SwUpDn = 0
Getting parameter: Quiet
Quiet = 0
Getting parameter: Tur
Tur = 0
Getting parameter: StHt
StHt = 0
Getting parameter: TemUn
TemUn = 0
Getting parameter: HeatCoolType
HeatCoolType = 0
Getting parameter: TemRec
TemRec = 0
Getting parameter: SvSt
SvSt = 0

This test are realise from homebridge server (the same IP which homebridge witch module use) SetTem and Mod are read correctly

**Comment by ddenisyuk** [comment]
@quartist 1.0.4 is available. Please check

**Comment by quartist** [comment]
@ddenisyuk

Solved! No crash loops and error on HB log. Only (-40C) problem persist.

**Comment by ddenisyuk** [comment]
@quartist please fetch "TemSen" using  https://github.com/tomikaa87/gree-remote

**Comment by ghost** [comment]
Better to pass an error to callback than return zero.
